---
- name: service module demo
  hosts: "{{hostname}}"
  become: true
  tasks:
    - name: Take action on "{{service_name}}" - "{{service_state}}"
      ansible.builtin.service:
        name: "{{service_name}}"
        state: "{{service_state}}"
        enabled: true
